[Container scalability] Implementation of MySqlBackupManager for managing account metadata on local disk
linkedin/ambry pull request #1627
Opened 2020-09-22 05:39 UTC by Arun-LinkedIn

Changes to:
1. Persist account and container metadata to local file on disk
2. Retrieve metadata from local file on start up and initialize cache.

2020-09-22 21:19 UTC, lightningrob commented on ambry-account/src/main/java/com/github/ambry/account/MySqlAccountService.java
> +    private static final Logger logger = LoggerFactory.getLogger(BackupFileManager.class);
MySqlBackupFileManager.  Also, this class is big enough to be in its own file.

2020-09-23 04:47 UTC, justinlin-linkedin reviewed
It looks pretty good to me, please add more unit tests to cover your new backup file implementation.

2020-09-23 04:47 UTC, justinlin-linkedin commented on ambry-account/src/main/java/com/github/ambry/account/MySqlAccountService.java
> +    static final Pattern filenamePattern = Pattern.compile(BACKUP_FILE_NAME + "\\.(\\d{8}T\\d{6})$");
you might want to also add a begin anchor of "^" for your pattern. Something like
`"^" + BACKUP_FILE_NAME + "......"`

2020-09-24 05:41 UTC, lightningrob requested changes

2020-09-25 03:29 UTC, jsjtzyy commented on ambry-api/src/main/java/com/github/ambry/config/MySqlAccountServiceConfig.java
> +  @Default("100")
minor: I guess you wanted to set 10 here.

2020-09-25 03:36 UTC, jsjtzyy commented on ambry-account/src/test/java/com/github/ambry/account/BackupFileManagerTest.java
> +import com.github.ambry.utils.SystemTime;
This import can be removed.

2020-09-25 03:50 UTC, jsjtzyy approved these changes

2020-09-25 05:38 UTC, lightningrob approved these changes
Looks good, especially the refactoring of BackupFileManager to make it generic and reusable.
Will merge once the build is green.

2020-09-25 17:41 UTC, lightningrob commented on ambry-api/src/test/java/com/github/ambry/account/AccountContainerTest.java
> +        containerJson.put(LAST_MODIFIED_TIME_KEY, container.getLastModifiedTime());
Is this needed in the old version?

2020-09-25 17:42 UTC, lightningrob commented on ambry-api/src/test/java/com/github/ambry/account/AccountContainerTest.java
> +import static com.github.ambry.account.Container.LAST_MODIFIED_TIME_KEY;
Not sure this was really needed.  Could have referenced it by class.

2020-09-25 18:26 UTC, merged