Changes to notify account updates in MySqlAccountService to consumers
linkedin/ambry pull request #1669
Opened 2020-10-22 22:33 UTC by Arun-LinkedIn

Contains following changes:
1. Notify account updates in MySqlAccountService to consumers
2. Add version field in Container

2020-10-27 01:28 UTC, lightningrob requested changes
Good refactoring.  Approved after minor changes.

2020-10-27 01:28 UTC, lightningrob commented on ambry-account/src/main/java/com/github/ambry/account/AbstractAccountService.java
> +        accountServiceMetrics.accountUpdatesToZkErrorCount.inc();
This seems like the wrong metric (or maybe needs name change).

2020-10-27 01:28 UTC, lightningrob commented on ambry-account/src/main/java/com/github/ambry/account/AccountUtils.java
> +   */
Minor: add @return line.

2020-10-27 04:08 UTC, jsjtzyy approved these changes
LGTM after a few minor comments are addressed

2020-10-27 04:08 UTC, jsjtzyy commented on ambry-account/src/main/java/com/github/ambry/account/AccountInfoMap.java
> +        return true;
Is there a unit test for this?

2020-10-27 04:08 UTC, jsjtzyy commented on ambry-account/src/main/java/com/github/ambry/account/MySqlAccountService.java
> +                  .build();
Same here, do we have unit test to verify the updated version?

2020-10-27 20:48 UTC, jsjtzyy approved these changes

2020-10-27 22:38 UTC, lightningrob approved these changes

2020-10-28 01:11 UTC, Arun-LinkedIn commented on ambry-api/src/main/java/com/github/ambry/account/Container.java
> +      int snapshotVersion) {
I think Yingyi added isSameContainer() recently to only compare user editable fields in Container. @jsjtzyy

2020-10-28 06:36 UTC, lightningrob commented
A few tests in MySqlAccountServiceIntegrationTest are failing.

2020-10-28 16:53 UTC, justinlin-linkedin approved these changes

2020-10-28 16:53 UTC, justinlin-linkedin commented on ambry-api/src/main/java/com/github/ambry/account/Container.java
> +      int snapshotVersion) {
Please add snapshotVersion in equals method.

2020-10-28 16:57 UTC, SophieGuo410 commented on ambry-account/src/main/java/com/github/ambry/account/AbstractAccountService.java
> +  public void selectInactiveContainersAndMarkInStore(StatsSnapshot statsSnapshot) {
@justinlin-linkedin , I'm still working on the orca job implementation(it's in a different MP ambry-ecl-tools). Currently it's working on my local. But still need to tested on EI and Prod. I'll remove the legacy code once I've done with the orca job implementation.

2020-10-28 18:04 UTC, merged