Add an admin request to return the persistent index values for a blob id
linkedin/ambry pull request #2193
Opened 2022-08-24 21:22 UTC by justinlin-linkedin

Add an admin request to return the index values for a blob id so every time when we are trying to see if a blob exists in a host, we don't have to dump all the index segment from that host.

2022-08-26 18:23 UTC, snalli reviewed
Some context as to why you are making all these changes would be relevant. Is this for a GCN ? If so, just paste the GCN number in the commit msg.

2022-08-26 19:08 UTC, snalli commented on ambry-server/src/main/java/com/github/ambry/server/AmbryServerRequests.java
> +      Collections.sort(messages, (m1, m2) -> (int) (m1.getOperationTimeMs() - m2.getOperationTimeMs()));
Why is this sort needed ?

2022-08-29 20:53 UTC, snalli commented on ambry-protocol/src/main/java/com/github/ambry/protocol/BlobIndexAdminRequest.java
> +    this.sizeInBytes = super.sizeInBytes() + Short.BYTES + BLOB_ID_LENGTH + blobId.length();
plus the Long.BYTES for sizeInBytes ?

2022-08-29 20:55 UTC, snalli commented on ambry-protocol/src/main/java/com/github/ambry/protocol/BlobIndexAdminRequest.java
> +    return "BlobIndexAdminRequest[ClientId=" + clientId + ", CorrelationId=" + correlationId + ", BlobId=" + blobId
String result;
result += "BlobIndexAdminRequest[ClientId=" + clientId;
result += ", CorrelationId=" + correlationId;
...

Just more readable

2022-08-29 20:55 UTC, snalli commented on ambry-protocol/src/test/java/com/github/ambry/protocol/RequestResponseTest.java
> +    AdminRequest adminRequest = new AdminRequest(AdminRequestOrResponseType.HealthCheck, null, correlationId, clientId);
is this part of this PR ? if not, can u make a separate PR ?

2022-08-29 20:58 UTC, snalli commented on ambry-server/src/main/java/com/github/ambry/server/AmbryServerRequests.java
> +        logger.error("BlobId {}'s partition[{}] doesn't exist in this host", blobId, partitionId.getId());
BlobId {}'s -> BlobId[{}]

2022-08-29 20:59 UTC, snalli commented on ambry-server/src/main/java/com/github/ambry/server/AmbryServerRequests.java
> +    }
Can there be an uncaught exception here ?

2022-08-29 21:00 UTC, snalli commented on ambry-store/src/main/java/com/github/ambry/store/BlobStore.java
> +          .map(value -> new MessageInfo(key, value.getSize(), value.isDelete(), value.isTtlUpdate(), value.isUndelete(),
how about create a new ctor like MessageInfo(key, value) ?

2022-08-29 23:15 UTC, snalli commented
Can u break this PR down ? Its too big

2022-08-31 05:41 UTC, snalli requested changes
requesting changes

2022-09-28 18:15 UTC, JingQianCloud reviewed
Nice tool which I'd like to have.
It's be helpful for me to test On-demand replication as well.

Just a feature requirement,
current the implementation is based on PersistentIndex.findAllIndexValuesForKey which returns List of IndexValue.
I wish I can get not only the IndexValues but also the Index Segment/Log Segment file names the IndexValues reside.
Wish we can have it in the next revision.

2022-09-30 17:30 UTC, tbingol approved these changes

2022-09-30 17:30 UTC, tbingol commented on ambry-server/src/main/java/com/github/ambry/server/AmbryServerRequests.java
> +      logger.error("Failed to convert {} to a BlobId", blobIndexAdminRequest.getBlobId(), e);
nit: s/blobIndexAdminRequest.getBlobId/blobIdStr

2022-10-12 05:38 UTC, ankagrawal reviewed
It looks like some of the changes of this PR are present in other PR. Are we planning to divide this PR into smaller PRs?

2022-10-12 20:10 UTC, justinlin-linkedin commented
> It looks like some of the changes of this PR are present in other PR. Are we planning to divide this PR into smaller PRs?

that's right, I will close this one.

2022-10-12 20:10 UTC, closed without merging