Adding a method to Store to return all the MessageInfos for a given key
linkedin/ambry pull request #2260
Opened 2022-10-13 00:09 UTC by justinlin-linkedin

Adding this method to Store/BlobStore for each query, to know if a host has any IndexValue for a given store key.

2022-10-13 04:49 UTC, JingQianCloud approved these changes
LGTM

2022-10-18 04:53 UTC, panchow requested changes

2022-10-19 18:18 UTC, justinlin-linkedin commented on ambry-api/src/main/java/com/github/ambry/store/Store.java
> +  default Map<String, MessageInfo> findAllMessageInfosForKey(StoreKey key) throws StoreException {
This is a tradeoff interface. This `Store` interface defines our storage engine. We currently have 3 different implementations for storage engine, 1 BlobStore that saves blob to a segmented index file and log file 2 InmemoryBlobStore used only for test 3 CloudBlobStore that saves blob to cosmosDB and ABS. This new method is only designed for the BlobStore.

There are some offset information from BlobStore that I want to return back to client, but Offset is not an command interface for all storage engine, it's an internal structure for BlobStore. That's why I want to convert the Offset as the key of this map. In this way, this method can still return the Offset information, without breaking the interface.

2022-10-20 00:24 UTC, panchow approved these changes

2022-10-20 00:24 UTC, merged