[WIP] s3BatchDelete
linkedin/ambry pull request #2965
Opened 2024-12-13 22:34 UTC by snalli

Skeleton PR

2025-01-15 19:22 UTC, justinlin-linkedin requested changes

2025-01-15 19:22 UTC, justinlin-linkedin commented on ambry-frontend/src/main/java/com/github/ambry/frontend/s3/S3BatchDeleteHandler.java
> +          S3MessagePayload.S3BatchDeleteObjects deleteRequest = xmlMapper.readValue(byteArray, S3MessagePayload.S3BatchDeleteObjects.class);
let's create a separate method for this logic.

2025-01-15 19:22 UTC, justinlin-linkedin commented on ambry-frontend/src/main/java/com/github/ambry/frontend/s3/S3BatchDeleteHandler.java
> +            RequestPath requestPath = (RequestPath) restRequest.getArgs().get(RestUtils.InternalKeys.REQUEST_PATH);
we need to save the original requestPath outside of for loop. Within forloop, the request path would be override.

2025-01-15 19:22 UTC, justinlin-linkedin commented on ambry-frontend/src/main/java/com/github/ambry/frontend/s3/S3BatchDeleteHandler.java
> +                }
We also want to differentiate the error cases. Some keys failed with NotFound, some keys failed with InternalServerError etc. Let's keep a map from key to its delete status?

2025-01-15 19:22 UTC, justinlin-linkedin commented on ambry-frontend/src/main/java/com/github/ambry/frontend/s3/S3BatchDeleteHandler.java
> +        }
this logic should be put into BatchDeleteCallback.

2025-01-21 06:14 UTC, snalli commented on ambry-api/src/main/java/com/github/ambry/frontend/NamedBlobPath.java
> +  // ->
can u clean up some of the code before submitting for review ? this will allow us to focus on the code that is actually changed instead of spending time figuring out what to look for.

2025-01-23 21:45 UTC, snalli commented on ambry-api/src/main/java/com/github/ambry/frontend/s3/S3MessagePayload.java
> +  public static class S3BatchDeleteKeys {
S3BatchDeleteKeys - does this class represent one key or a list of keys ?

2025-01-23 21:46 UTC, snalli commented on ambry-api/src/main/java/com/github/ambry/frontend/s3/S3MessagePayload.java
> +    private List<String> success;
why is success called errors ?

2025-01-23 21:54 UTC, snalli commented on ambry-frontend/src/main/java/com/github/ambry/frontend/s3/S3BatchDeleteHandler.java
> +
PLease write it this way.
```
      S3MessagePayload.S3BatchDeleteObjects deleteRequest = deserializeRequest(channel);
      if (failedRequest || delete == null) {
          return immediately
      }

      // continue with the rest
```

2025-01-23 21:56 UTC, snalli commented on ambry-frontend/src/main/java/com/github/ambry/frontend/s3/S3BatchDeleteHandler.java
> +  public void onDeleteCompletion(boolean success, String key) {
This fn can be folded into the call site. It's small and not called anywhere else.

2025-01-23 22:12 UTC, snalli commented on ambry-frontend/src/main/java/com/github/ambry/frontend/s3/S3BatchDeleteHandler.java
> +          deleteBlobHandler.handle(singleDeleteRequest, noOpResponseChannel, new Callback<Void>() {
Pleaes consider this 

```
          // Handle the delete operation using the deleteBlobHandler
          deleteBlobHandler.handle(singleDeleteRequest, noOpResponseChannel, (result, exception) -> {
            // Call our custom onDeleteCompletion to track success/failure
            restRequest.getArgs().remove("ambry-internal-key-target-account");
            restRequest.getArgs().remove("ambry-internal-key-keep-alive-on-error-hint");
            restRequest.getArgs().remove("ambry-internal-key-target-container");
            if (exception == null) {
              deleted.add(object.getKey());
            } else {
              errors.add(object.getKey());
            }
            // Decrement latch to signal that this delete operation has finished
            latch.countDown();
          });
```

2025-01-23 22:13 UTC, snalli commented on ambry-frontend/src/main/java/com/github/ambry/frontend/s3/S3BatchDeleteHandler.java
> +            public void onCompletion(Void result, Exception exception) {
Use a lambda instead of creating `Callback`.
`args` is unused, `success` can be removed as it is a single-use variable.

2025-01-23 22:14 UTC, snalli commented on ambry-frontend/src/main/java/com/github/ambry/frontend/s3/S3BatchDeleteHandler.java
> +            Thread.currentThread().interrupt();
We should probably print something here and may be emit a metric ?

2025-01-23 22:15 UTC, snalli commented on ambry-frontend/src/main/java/com/github/ambry/frontend/s3/S3BatchDeleteHandler.java
> +        for (S3MessagePayload.S3BatchDeleteKeys object : deleteRequest.getObjects()) {
This loop growing too large. Consider combining some pieces of it into descriptive functions.

2025-01-23 22:57 UTC, justinlin-linkedin commented on ambry-frontend/src/main/java/com/github/ambry/frontend/s3/S3BatchDeleteHandler.java
> +        Map<String, CompletableFuture<Void>> deleteFutures = new HashMap<>();
I suppose we are not actually using these keys, we can just create a list instead of map.

2025-01-23 22:57 UTC, justinlin-linkedin commented on ambry-frontend/src/main/java/com/github/ambry/frontend/s3/S3BatchDeleteHandler.java
> +          allDeletes.get();  // This will throw an exception if any future fails
We don't want to block here, get() would block.
We want to do something like 
```
CompletableFuture.allOf(deletedFutures.values().toArray(new CompletableFuture[0])).whenComplete((v, exception) -> {
    // we should ignore exception, since we catch errors in the deleted and errors fields.
    // final callback
    if (failedRequest) {
        ....
    } else {
        // construct response
        callback.onComplete(xxx);
    }
});
```

In this way, the completable future is not going to block.

2025-01-24 00:16 UTC, snalli commented on ambry-frontend/src/main/java/com/github/ambry/frontend/s3/S3BatchDeleteHandler.java
> +  }
+ metrics 
+ logging
+ error handling
+ minor stuff

2025-01-28 00:38 UTC, justinlin-linkedin commented on ambry-api/src/main/java/com/github/ambry/rest/RequestPath.java
> +
we don't need this empty line.

2025-01-28 00:38 UTC, justinlin-linkedin commented on ambry-frontend/src/main/java/com/github/ambry/frontend/s3/S3BaseHandler.java
> +  public static boolean isBatchDelete(RestRequest restRequest) {
please add some comments for this method.

2025-01-28 00:38 UTC, justinlin-linkedin commented on ambry-frontend/src/main/java/com/github/ambry/frontend/s3/S3BatchDeleteHandler.java
> +package com.github.ambry.frontend.s3;
we need to put the license information here.

2025-01-28 00:38 UTC, justinlin-linkedin commented on ambry-frontend/src/main/java/com/github/ambry/frontend/s3/S3BatchDeleteHandler.java
> +  private ArrayList<S3MessagePayload.S3DeleteError> errors = new ArrayList<>();
Request specific variables should not be handler members.

2025-01-28 00:38 UTC, justinlin-linkedin commented on ambry-frontend/src/main/java/com/github/ambry/frontend/s3/S3BatchDeleteHandler.java
> +        metrics.deleteBlobMetricsGroup.getRestRequestMetrics(restRequest.isSslUsed(), false);
it should be `metrics.batchDeleteBlobMetricsGroup.getRestRequestMetrics`.

2025-01-28 19:50 UTC, snalli commented on ambry-api/src/main/java/com/github/ambry/frontend/s3/S3MessagePayload.java
> +      return "S3BatchDeleteKeys{" +
S3BatchDeleteKey

2025-01-28 19:52 UTC, snalli commented on ambry-frontend/src/main/java/com/github/ambry/frontend/s3/S3BatchDeleteHandler.java
> +        throw new RestServiceException("bytesRead is empty", RestServiceErrorCode.BadRequest);
I am not sure but do we need to adhere to S3 error messages ?

2025-01-28 19:53 UTC, snalli commented on ambry-frontend/src/main/java/com/github/ambry/frontend/s3/S3BatchDeleteHandler.java
> +
The whitespace formatting and the position of newlines is odd.

2025-01-28 19:54 UTC, snalli commented on ambry-frontend/src/main/java/com/github/ambry/frontend/s3/S3BatchDeleteHandler.java
> +              LOGGER.error("Failed to complete", e);
space after "complete "

2025-01-28 19:56 UTC, snalli commented on ambry-frontend/src/main/java/com/github/ambry/frontend/s3/S3BatchDeleteHandler.java
> +  private final int maxBatchSize = 1000;
There is a file S3Constants. Please move it there as MAX_BATCH_DELETE_SIZE.

2025-01-28 20:02 UTC, snalli commented on ambry-frontend/src/main/java/com/github/ambry/frontend/s3/S3BatchDeleteHandler.java
> +        LOGGER.error("Exceeded batch size");
A more informative errmsg could be 
```
LOGGER.error("Exceeded maximum batch size of ", MAX_BATCH_DELETE_SIZE);
```
Create one string and use it in both places - to print log and to pass in the RestServiceException

2025-01-28 20:02 UTC, snalli commented on ambry-frontend/src/main/java/com/github/ambry/frontend/s3/S3BatchDeleteHandler.java
> +            RequestPath.parse(singleDeletePath, restRequest.getArgs(), emptyList, requestPath.getClusterName());
directly pass new ArrayList<>()

2025-01-28 20:04 UTC, snalli commented on ambry-frontend/src/main/java/com/github/ambry/frontend/s3/S3BatchDeleteHandler.java
> +      throw new RestServiceException("failed to deserialize",e, RestServiceErrorCode.BadRequest);
whitspaces here
```
throw new RestServiceException("Failed to deserialize batch-delete due to ", e, RestServiceErrorCode.BadRequest);
```

2025-01-28 20:08 UTC, snalli commented on ambry-frontend/src/main/java/com/github/ambry/frontend/s3/S3BatchDeleteHandler.java
> +    }
```
if () {
} else {
}
```

2025-01-28 20:11 UTC, snalli commented on ambry-frontend/src/main/java/com/github/ambry/frontend/s3/S3BatchDeleteHandler.java
> +      deleted.add(key);
Multiple threads are going to call this fn concurrently. Do we need a some lock or a concurrent data structure here ?

2025-01-28 22:52 UTC, snalli commented on ambry-frontend/src/main/java/com/github/ambry/frontend/s3/S3BatchDeleteHandler.java
> +          .whenComplete((result, exception) -> {
How does this `whenComplete` ? Does the last thread that completes the single delete-req call into whenComplete ?

2025-01-29 23:54 UTC, allenaverbukh commented on ambry-frontend/src/main/java/com/github/ambry/frontend/s3/S3BatchDeleteHandler.java
> +        throw new RestServiceException("bytesRead is empty", RestServiceErrorCode.BadRequest);
@justinlin-linkedin , i kept it like this since the response does not directly provide an error message when it fails to read bytes or encounters other issues. Instead, the response typically indicates success or failure on the level of individual object deletions within the batch .. at least that is my perception

2025-01-30 00:12 UTC, justinlin-linkedin commented on ambry-frontend/src/main/java/com/github/ambry/frontend/s3/S3BatchDeleteHandler.java
> +              String xmlDeclaration = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n";
Let' use xmlMapper's configuration for this task
```
xmlMapper.configure(ToXmlGenerator.Feature.WRITE_XML_DECLARATION, true);
```
when creating this xmlMapper

2025-01-30 00:12 UTC, justinlin-linkedin commented on ambry-api/src/main/java/com/github/ambry/frontend/s3/S3MessagePayload.java
> +
These object is just for serialization and deserialization, we don't need to use concurrent data structure for them.
Could you please use just ArrayList, and convert a concurrent linked queue to array list in setErrors and setDeleted?

2025-01-30 00:52 UTC, justinlin-linkedin commented on ambry-frontend/src/main/java/com/github/ambry/frontend/s3/S3BatchDeleteHandler.java
> +        throw new RestServiceException("bytesRead is empty", RestServiceErrorCode.BadRequest);
We don't have to print these error message here since it's from client. Add error message would pollute our loggings. That being said, batch delete's error message would be send back to client in response body. We will do that in next PR. So for now, we can drop it.

2025-01-30 01:02 UTC, justinlin-linkedin approved these changes

2025-01-30 21:41 UTC, snalli commented
@allenaverbukh 
PR Title: Enabled S3BatchDelete 
Description : 
This PR implements S3BatchDelete API. Each requests takes multiple keys to delete and a returns a batch response including the status of delete - success or fail - for each key.

2025-01-30 21:48 UTC, snalli commented on ambry-frontend/src/main/java/com/github/ambry/frontend/s3/S3BatchDeleteHandler.java
> +      }
Please write it this way

```
      // first thing to do is validate the request
      ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
      ReadableStreamChannel readableStreamChannel =
          new ByteBufferReadableStreamChannel(ByteBuffer.wrap(outputStream.toByteArray()));
      S3MessagePayload.S3BatchDeleteObjects deleteRequest = deserializeRequest(channel);
      if (deleteRequest.getObjects().size() > MAX_BATCH_DELETE_SIZE) {
        String batchSizeErrorMessage = "Exceeded Maximum Batch Size of ";
        throw new RestServiceException(batchSizeErrorMessage, RestServiceErrorCode.BadRequest);
      }


      // next create objects to process the request
      S3MessagePayload.DeleteResult response = new S3MessagePayload.DeleteResult();
      ConcurrentLinkedQueue<S3MessagePayload.S3ErrorObject> errors = new ConcurrentLinkedQueue<>();
      ConcurrentLinkedQueue<S3MessagePayload.S3DeletedObject> deleted = new ConcurrentLinkedQueue<>();
      RequestPath requestPath = (RequestPath) restRequest.getArgs().get(InternalKeys.REQUEST_PATH);


```

2025-01-30 21:51 UTC, snalli commented on ambry-frontend/src/main/java/com/github/ambry/frontend/s3/S3BatchDeleteHandler.java
> +      S3MessagePayload.S3BatchDeleteObjects deleteRequest = deserializeRequest(channel);
something seems odd, how are u deserializing the request from user ? L97 creates an new output stream that has nothing to do with user request.

2025-01-30 21:51 UTC, snalli commented on ambry-frontend/src/main/java/com/github/ambry/frontend/s3/S3BatchDeleteHandler.java
> +          .whenComplete((result, exception) -> {
Can you answer this please ?

2025-01-30 22:23 UTC, allenaverbukh commented on ambry-frontend/src/main/java/com/github/ambry/frontend/s3/S3BatchDeleteHandler.java
> +          .whenComplete((result, exception) -> {
The whenComplete method is triggered when the associated CompletableFuture (like your delete-req) completes, regardless of which thread finishes it. It’s not dependent on the "last" thread to finish. Each delete-req will invoke its own whenComplete once that specific future completes, independently of the order in which multiple futures finish. So, the execution of whenComplete depends on when each future completes, not on the last thread.

if you can confirm this @justinlin-linkedin

2025-01-30 22:50 UTC, justinlin-linkedin commented on ambry-frontend/src/main/java/com/github/ambry/frontend/s3/S3BatchDeleteHandler.java
> +          .whenComplete((result, exception) -> {
when all the completable futures finish, the when complete callback will be invoked in the fork-join thread pool.

2025-01-30 23:56 UTC, snalli commented on ambry-frontend/src/main/java/com/github/ambry/frontend/s3/S3BatchDeleteHandler.java
> +          .whenComplete((result, exception) -> {
Thanks, i wanted to know which thread runs whenCompelte

2025-01-30 23:56 UTC, snalli reviewed
LGTM

2025-01-30 23:59 UTC, allenaverbukh approved these changes

2025-01-31 00:02 UTC, merged